import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import {DemoReel, Project} from "@/app/components/Data";

const quicksandSans = Quicksand({
    variable: "--font-quicksand-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
    demo_reels: DemoReel[];
    projects: Project[];
    children: React.ReactNode;
}

export default function RootLayout({
   demo_reels,
   projects,
   children
}: LayoutProps) {

    if (!demo_reels || demo_reels.length === 0) console.error("Error on demo reels.");
    if (!projects || projects.length === 0) console.error("Error on projects.");

    return (
    <html lang="en">
      <body className={`${quicksandSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
