import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";

const quicksandSans = Quicksand({
    variable: "--font-quicksand-sans",
    subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface LayoutProps {
    demo_reels: any;
    projects: any;
    children: React.ReactNode;
}

export default function RootLayout({
  children
}: LayoutProps) {
  return (
    <html lang="en">
      <body className={`${quicksandSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
